### ISSUE TITLE
Contribute Comparator?

### ISSUE THREAD

**Issue by chancharles** [pgilad/gulp-sort#2]
Not sure where to contribute a comparator. I wrote one that compare the file path based on how deep the directory structure is and then based on alpha.

``` javascript
        comparator: function (f1, f2) {
          /*
           * Sort path based on directory and alpha. The deeper the directory, the higher the order.
           */
          function comparePathComponent(c1, c2) {
            var slash1 = c1.indexOf(path.sep);
            var slash2 = c2.indexOf(path.sep);
            if (slash1 < 0) {
              if (slash2 > 0) {
                return 1;
              } else if (slash2 < 0) {
                return c1.localeCompare(c2);
              }
            } else {
              if (slash2 > 0) {
                var sub1 = c1.substring(0, slash1);
                var sub2 = c2.substring(0, slash2);
                if (sub1.localeCompare(sub2) === 0) {
                  return comparePathComponent(c1.substring(slash1 + 1), c2.substring(slash2 + 1));
                } else {
                  return sub1.localeCompare(sub2);
                }
              } else if (slash2 < 0) {
                return -1;
              }
            }
          }

          return comparePathComponent(f1.path, f2.path);
        }
```

**Comment by pgilad** [comment]
First off: great thought! :tophat: 
I would rather keep `gulp-sort` really small and modular and have links/refs/documentation to patterns.

What I would do:
1. Open a repository for your sort method (say `sort-path-by-depth` or something)
2. Test the comparator to the bone (because it's obviously also useful for other build tools/etc)
3. We can add a reference to recommended comparators in this repository (say a section in the readme)
4. Also, because this is actually the first comparator being submitted, we can add a usage section for using an external comparator. (i.e best practice). What I would do:

``` js
import sort from 'gulp-sort';
import sortPathByDepth from 'sort-path-by-depth';

//.. gulp stream
.pipe(sort(sortPathByDepth))
//... continue stream
```

And again - thanks for the addition. PRs are welcome for the above recommendations!

**Comment by chancharles** [comment]
Make sense. I will close this issue and let you know as soon as I proceed further with this.
